"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// import { Person } from "./oops";
var oops_1 = require("./oops");
var personObj = new oops_1.default("Nirmal", 99999, "Chennai", true);
personObj.personDetails();
var personObj1 = new oops_1.default("Sandhya", 101010, "Chennai", true);
personObj1.personDetails();
var personObj2 = new oops_1.default("Malak", 11111, "Chennai", true);
personObj2.personDetails();
